from enum import Enum

class StatutS2I(Enum):
    ACTIF = "ACTIF"
    ARCHIVE = "ARCHIVE"
    PENDING_MOOVAPS = "PENDING_MOOVAPS"
    PENDING_E_PRODUITS = "PENDING_E_PRODUITS"
    REJETE_MOOVAPS = "REJETE_MOOVAPS"
    REJETE_E_PRODUITS = "REJETE_E_PRODUITS"