from enum import Enum

class StatutS2I(Enum):
    ACTIF = "ACTIF"
    ARCHIVE = "ARCHIVE"
    PENDING_MOOVAPS = "PENDING_MOOVAPS"
    PENDING_E_PRODUITS = "PENDING_E_PRODUITS"
    REJETE_MOOVAPS = "REJETE_MOOVAPS"
    REJETE_E_PRODUITS = "REJETE_E_PRODUITS"
    
    
class DocTypeEnum(Enum):
    HEBERGEMENT_TOURISTIQUE = "HEBERGEMENT_TOURISTIQUE"
    ANIMATION_TOURISTIQUE = "ANIMATION_TOURISTIQUE"
    AMENAGEMENT_TOURISTIQUE = "AMENAGEMENT_TOURISTIQUE"
    SIGNALETIQUE_TOURISTIQUE = "SIGNALETIQUE_TOURISTIQUE"
    RESTAURATION_PRODUCT = "RESTAURATION_PRODUCT"

    OPPORTUNITE_HEBERGEMENT = "OPPORTUNITE_HEBERGEMENT"
    OPPORTUNITE_FONCIER = "OPPORTUNITE_FONCIER"
    RESSOURCE_FONCIERE = "RESSOURCE_FONCIERE"
    RESSOURCE_TOURISTIQUE = "RESSOURCE_TOURISTIQUE"
    TOURIST_PACKAGE = "TOURIST_PACKAGE"
    MARKETPLACE = "MARKETPLACE"